main: "cc.dreamcode.ffa.BukkitFFAPlugin"
version: "1.0-beta.1"
name: "Dream-FFA"
description: "Dream-FFA plugin written by dreamcode.cc"
website: "https://dreamcode.cc"
author: "vkie"
api-version: 1.16

softdepend:
  - 'PlaceholderAPI'